shell = "/usr/bin/mksh"

[window]
startup_mode = "Fullscreen"
decorations_theme_variant = "Dark"
option_as_alt = "Both"	# macos

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = true

[colors]
[colors.primary]
background = "#0c0c0c"
foreground = "#cccccc"
[colors.normal]
black =      "#0c0c0c"
red =        "#c50f1f"
green =      "#13a10e"
yellow =     "#c19c00"
blue =       "#0037da"
magenta =    "#881798"
cyan =       "#3a96dd"
white =      "#cccccc"
[colors.bright]
black =      "#767676"
red =        "#e74856"
green =      "#16c60c"
yellow =     "#f9f1a5"
blue =       "#3b78ff"
magenta =    "#b4009e"
cyan =       "#61d6d6"
white =      "#f2f2f2"

# [keyboard]
# bindings = [
#   { "Add",   "Control", "AppCursor | AppKeypad | Search | Alt | Vi", "IncreaseFontSize" }
# ]
